services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=moviehub
      - DATABASE_PASSWORD=moviehub123
      - DATABASE_NAME=moviehub
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TMDB_API_KEY=${TMDB_API_KEY}
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=moviehub
      - POSTGRES_USER=moviehub
      - POSTGRES_PASSWORD=moviehub123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
